export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_POPULARMOVIES = 'GET_POPULARMOVIES';
export const ADD_FAVORITEMOVIE = 'ADD_FAVORITEMOVIE';
export const GET_FAVORITEMOVIES = 'GET_FAVORITEMOVIES';

export const FAVORITE_ERROR = 'FAVORITE_ERROR';

export const SET_LOADING = 'SET_LOADING';

export const SET_TEXT = 'SET_TEXT';
export const LOAD_MOREPAGES = 'LOAD_MOREPAGES';
export const RESET_MOVIES = 'RESET_MOVIES';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT'

